In [30]:
import pandas as pd
import numpy as np

In [31]:


data = {
    "Student" : ["A","B","C","D","E"],
    "Gender" : ["Male","Female","Male","Female","Male"],
    "StudyHours" : [5,6,np.nan,4,7],
    "Attendance" : [80,85,75,np.nan,90],
    "Marks" : [75,82,68,5,np.nan],
    "Result" : ["PASS","PASS","PASS","FAIL","PASS"],
}

In [32]:
df = pd.DataFrame(data)

display(df)

  Student  Gender  StudyHours  Attendance  Marks Result
0       A    Male         5.0        80.0   75.0   PASS
1       B  Female         6.0        85.0   82.0   PASS
2       C    Male         NaN        75.0   68.0   PASS
3       D  Female         4.0         NaN    5.0   FAIL
4       E    Male         7.0        90.0    NaN   PASS

In [33]:
print(df.isnull().sum())

Student       0
Gender        0
StudyHours    1
Attendance    1
Marks         1
Result        0
dtype: int64

In [34]:
df["StudyHours"] = df["StudyHours"].fillna(
    df["StudyHours"].mean()
)
display(df)

  Student  Gender  StudyHours  Attendance  Marks Result
0       A    Male         5.0        80.0   75.0   PASS
1       B  Female         6.0        85.0   82.0   PASS
2       C    Male         5.5        75.0   68.0   PASS
3       D  Female         4.0         NaN    5.0   FAIL
4       E    Male         7.0        90.0    NaN   PASS

In [35]:
df["Marks"] = df["Marks"].fillna(
    df["Marks"].median()
)
display(df)

  Student  Gender  StudyHours  Attendance  Marks Result
0       A    Male         5.0        80.0   75.0   PASS
1       B  Female         6.0        85.0   82.0   PASS
2       C    Male         5.5        75.0   68.0   PASS
3       D  Female         4.0         NaN    5.0   FAIL
4       E    Male         7.0        90.0   71.5   PASS

In [46]:
df["Attendance"] = df["Attendance"].ffill()
display(df)

  Student  Gender  StudyHours  Attendance  Marks Result
0       A     NaN         5.0        80.0   75.0   PASS
1       B     NaN         6.0        85.0   82.0   PASS
2       C     NaN         5.5        75.0   68.0   PASS
3       D     NaN         4.0        75.0    5.0   FAIL
4       E     NaN         7.0        90.0   71.5   PASS

In [45]:
df["Gender"] = df["Gender"].astype(str).str.strip().str.title()

df["Gender"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})

display(df)

  Student  Gender  StudyHours  Attendance  Marks Result
0       A     NaN         5.0        80.0   75.0   PASS
1       B     NaN         6.0        85.0   82.0   PASS
2       C     NaN         5.5        75.0   68.0   PASS
3       D     NaN         4.0        75.0    5.0   FAIL
4       E     NaN         7.0        90.0   71.5   PASS

In [42]:
print(df['Gender'].unique())

  Student  Gender  StudyHours  Attendance  Marks Result
0       A     NaN         5.0        80.0   75.0   PASS
1       B     NaN         6.0        85.0   82.0   PASS
2       C     NaN         5.5        75.0   68.0   PASS
3       D     NaN         4.0        75.0    5.0   FAIL
4       E     NaN         7.0        90.0   71.5   PASS

In [44]:
print(df["Gender"].unique())
df["Gender"] = df["Gender"].map({
    "Male" : 1,
    "Female" : 0
    
})
display(df)

[nan]

  Student  Gender  StudyHours  Attendance  Marks Result
0       A     NaN         5.0        80.0   75.0   PASS
1       B     NaN         6.0        85.0   82.0   PASS
2       C     NaN         5.5        75.0   68.0   PASS
3       D     NaN         4.0        75.0    5.0   FAIL
4       E     NaN         7.0        90.0   71.5   PASS